server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: local
    include:
      - aws
      - auth
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    view:
      suffix: .html
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE




