server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: local
    include:
      - aws
      - auth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE




